AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  redditapipipeline:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::654943956818:role/service-role/reddit-api-pipeline-role-pt6d2ole
      Layers:
        - 'arn:aws:lambda:us-east-2:336392948345:layer:AWSDataWrangler-Python39:7'
        - 'arn:aws:lambda:us-east-2:654943956818:layer:reddit-api-layer:5'
